### PR TITLE
Corrected example dataset description in README.md

### PR DESCRIPTION
**Pull request by sanjaydasgupta**
This PR corrects the issue reported in https://github.com/DeDolphins/DataHorse/issues/21

### CODE REVIEW

**Comment by sanjaydasgupta** [comment]
Thank you for accepting the PR @SsebowaDisan.

I noticed that the linked [colab notebook](https://colab.research.google.com/drive/1brAw2Qj_VnlTbzcfjm5sCOaQbNl7Disd?usp=sharing) also has the same issue, but am unable to locate the source within the repo. 

This is a very small problem, and you can fix it yourself, but if you want me do it please let me know how to proceed.

Thank you.

**Comment by SsebowaDisan** [comment]
Thank you for pointing this out! @sanjaydasgupta  I went ahead and solved the issue in the linked Colab notebook as well. Appreciate your contribution a lot! 

Thanks once again.

**Comment by sanjaydasgupta** [comment]
Do you have a roadmap for future plans @SsebowaDisan ? Or a list of other products from which you draw inspiration for this?

Do you think adding a few lines on that to your README may help to align potential contributors' suggestions?

**Comment by SsebowaDisan** [comment]
Thanks @sanjaydasgupta for asking! We have a developing roadmap. Key upcoming features include:

1. Attach your own model  
2. Attach your own API  
3. Connect to databases  
4. Generate reports of the analysis  
5. Improve our web app to resemble Jupyter Notebook/Google Colab UI

Yes, that's a great idea! we will add a few lines to the README to better align potential contributors' suggestions. Thanks for the tip!

We will add these to the README soon to align suggestions. Would you be interested in helping with this? Your input would be invaluable!

**Comment by sanjaydasgupta** [comment]
Thanks for your response @SsebowaDisan.

I do not have much free time, but would love to contribute whenever I am able.

**Comment by SsebowaDisan** [comment]
Thanks for your willingness to contribute @sanjaydasgupta! I completely understand the time constraints. Feel free to jump in whenever you're available, and your contributions will always be appreciated.

**Pull request merged**
